name = "Hnu"
uuid = "a1272aa4-dd8a-4b98-8998-982c36939de1"
version = "0.1.0"
authors = ["Julian Kuhlmann <kuhlmann@mpp.mpg.de>"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SkyCoords = "fc659fc5-75a3-5475-a2ea-3da92c065361"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DelimitedFiles = "1.9.1"
IJulia = "1.33.0"
Interpolations = "0.16.2"
Plots = "1.41.4"
Revise = "3.13.1"
SkyCoords = "1.7.0"
Unitful = "1.27.0"
